### PR TITLE
Update to v1.3.0 and switch to noarch

### PR DESCRIPTION
**Pull request by rth**
Update to v1.3.0 and switch to noarch

### CODE REVIEW

**Comment by rth** [comment]
So the build on master failed on CircleCI (noarch) for [PY2.7](https://circleci.com/gh/conda-forge/freediscovery-feedstock/17?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), [PY.3.5](https://circleci.com/gh/conda-forge/freediscovery-feedstock/18?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) but passed for [PY3.6](https://circleci.com/gh/conda-forge/freediscovery-feedstock/19?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), with an error very similar to https://github.com/conda-forge/conda-forge.github.io/issues/426 about failing to upload to anaconda (traceback below). I do see @isuruf 's commit with the updated anaconda token, though. This PR also updated to noarch, in case it's relevant.

Not sure what the issue is, or whom I should ping for guidance in cases like this (i.e. is there a dedicated `@<team-alias>`)?..  cc @jakirkham @ocefpaf Thanks!

```
Traceback (most recent call last):
  File "/opt/conda/bin/upload_or_check_non_existence", line 122, in <module>
    main()
  File "/opt/conda/bin/upload_or_check_non_existence", line 111, in main
    upload(cli, meta, owner, channel)
  File "/opt/conda/bin/upload_or_check_non_existence", line 62, in upload
    env=os.environ)
  File "/opt/conda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['anaconda', '--quiet', '-t', 'binstar.token', 'upload', '/feedstock_root/build_artefacts/noarch/freediscovery-1.3.0-py_0.tar.bz2', '--user=conda-forge', '--channel=main']' returned non-zero exit status 1.
```

**Comment by isuruf** [comment]
You need to rerender the feedstock.

**Comment by rth** [comment]
@isuruf I did rerender with conda-smithy 2.4.1 in this PR (the 2.4.2 was failing for some reason due to https://github.com/conda-forge/conda-smithy/issues/552) and that seemed to build CI fine before I merged, after which it failed on master. 

Are you saying that I should make another PR with a rerendered feedstock to 2.4.2 ?

**Comment by isuruf** [comment]
I see multiple builds (for different python versions) with CircleCI, which is unnecessary and should be removed by a rerender.

**Comment by rth** [comment]
Aww I see, so it uploaded fine, but I guess since the other builds were attempting to upload an already existing build this failed.

Yeah, the re-rendering didn't go very smoothly, something might have gone wrong. Will re-render again. Thanks for your help! @isuruf

**Comment by isuruf** [comment]
FYI, you'll see an error again because of https://github.com/conda-forge/conda-forge-build-setup-feedstock/issues/80

**Comment by isuruf** [comment]
Also, there's https://conda-forge.org/docs/webservice.html#conda-forge-admin-please-rerender  if rerendering doesn't work locally.

**Comment by rth** [comment]
Got it, thanks!

> Also, there's https://conda-forge.org/docs/webservice.html#conda-forge-admin-please-rerender if rerendering doesn't work locally

That sounds great, I was tempted to try it..

**Comment by rth** [comment]
@isuruf Re-rendering worked. Thanks again!

**Pull request merged**
